Dev/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('post.urls')),
    path('', include('tag.urls')),
    path('', include('users.urls')),
    path('dashboard/', include('dashboard.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from .views import (
    RegisterView, LoginView, LogoutView, ProfileView, SettingsView, FollowToggle
)


urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('settings/', SettingsView.as_view(), name='settings'),
    path('<str:username>/', ProfileView.as_view(), name='profile'),
    path('follow/<str:username>/', FollowToggle.as_view(), name='follow_toggle'),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.dispatch import receiver
from django.db.models.signals import post_save


class Profile(AbstractUser):
    display_email = models.BooleanField(default=False)
    image = models.ImageField(default="no_user.png", upload_to='user_images')

    def __str__(self):
        return self.username


class Basic(models.Model):
    profile = models.OneToOneField(Profile, on_delete=models.CASCADE)
    site = models.CharField(max_length=100, null=True, blank=True)
    location = models.CharField(max_length=100, null=True, blank=True)
    bio = models.CharField(max_length=200, null=True, blank=True)

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.profile}'s basic"


class Coding(models.Model):
    profile = models.OneToOneField(Profile, on_delete=models.CASCADE)
    current = models.CharField(max_length=200, null=True, blank=True)
    skills = models.CharField(max_length=200, null=True, blank=True)

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.profile}'s coding"


class Work(models.Model):
    profile = models.OneToOneField(Profile, on_delete=models.CASCADE)
    work = models.CharField(max_length=100, null=True, blank=True)
    education = models.CharField(max_length=100, null=True, blank=True)

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.profile}'s work"


class Follow(models.Model):
    follower = models.ForeignKey(Profile, related_name='following', on_delete=models.CASCADE)
    following = models.ForeignKey(Profile, related_name='followers', on_delete=models.CASCADE)

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        unique_together = ('following', 'follower')

    def __str__(self):
        return f"{self.follower} follows {self.following}"


@receiver(post_save, sender=Profile)
def create_user_profile_basic(sender, instance, created, *args, **kwargs):
    if created:
        profile_basic_data = [Basic, Coding, Work]
        for basic in profile_basic_data:
            new_basic = basic.objects.create(
                profile=instance
            )
            new_basic.save()

users/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django import forms

from .models import Profile, Basic, Coding, Work

text_input_class = 'border border-gray-300 text-black font-semibold text-sm rounded-lg w-full p-2.5 ' \
                   'focus:ring-purple-700 focus:border-purple-700 dark:bg-black dark:border-zinc-700 ' \
                   'dark:placeholder-gray-400 dark:hover:border-zinc-600 dark:text-white'


class RegistrationForm(UserCreationForm):
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class': text_input_class}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class': text_input_class}))

    class Meta:
        model = Profile
        fields = ['username', 'email', 'password1', 'password2']

        widgets = {
            'username': forms.TextInput(attrs={'class': text_input_class}),
            'email': forms.EmailInput(attrs={'class': text_input_class}),
        }


class LoginForm(AuthenticationForm):
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': text_input_class}))
    username = forms.CharField(widget=forms.TextInput(attrs={'class': text_input_class}))


class ProfileModelForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['email', 'display_email', 'first_name', 'last_name', 'image']
        widgets = {
            'first_name': forms.TextInput(attrs={'class': text_input_class}),
            'last_name': forms.TextInput(attrs={'class': text_input_class}),
            'email': forms.EmailInput(attrs={'class': text_input_class}),
            'display_email': forms.CheckboxInput(attrs={
                'class': 'bg-gray-100 rounded focus:ring-purple-700 dark:border-zinc-700 dark:bg-black'
            }),
            'image': forms.FileInput(attrs={
                'class': 'col-span-9 text-sm text-black border border-gray-300 '
                         'rounded-lg cursor-pointer focus:ring-purple-700 focus:border-purple-700 '
                         'dark:text-zinc-600 dark:border-zinc-700 dark:bg-black'
            }),
        }


class BasicModelForm(forms.ModelForm):
    class Meta:
        model = Basic
        fields = ['site', 'location', 'bio']
        widgets = {
            'site': forms.TextInput(attrs={'class': text_input_class}),
            'location': forms.TextInput(attrs={'class': text_input_class}),
            'bio': forms.TextInput(attrs={'class': text_input_class})
        }


class CodingModelForm(forms.ModelForm):
    class Meta:
        model = Coding
        fields = ['current', 'skills']
        widgets = {
            'current': forms.TextInput(attrs={'class': text_input_class}),
            'skills': forms.TextInput(attrs={'class': text_input_class}),
        }


class WorkModelForm(forms.ModelForm):
    class Meta:
        model = Work
        fields = ['work', 'education']
        widgets = {
            'work': forms.TextInput(attrs={'class': text_input_class}),
            'education': forms.TextInput(attrs={'class': text_input_class}),
        }

users/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect, reverse
from django.shortcuts import get_object_or_404
from django.contrib.auth import login, logout
from django.views import View

from post.models import Post
from .forms import (
    ProfileModelForm, WorkModelForm, CodingModelForm,
    BasicModelForm, RegistrationForm, LoginForm
)
from .models import Profile, Follow


class RegisterView(View):
    def get(self, request):
        form = RegistrationForm()
        context = {
            'form': form
        }
        return render(request, 'registration.html', context)

    def post(self, request):
        form = RegistrationForm(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('login')
        else:
            context = {
                'form': form
            }
            return render(request, 'registration.html', context)


class LoginView(View):
    def get(self, request):
        form = LoginForm()
        context = {
            'form': form
        }
        return render(request, 'login.html', context)

    def post(self, request):
        form = LoginForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            next = request.GET.get('next') if request.GET.get('next') else ''
            return redirect('home' + next)
        else:
            context = {
                'form': form
            }
            return render(request, 'login.html', context)


class LogoutView(LoginRequiredMixin, View):
    def get(self, request):
        return render(request, 'logout.html')

    def post(self, request):
        logout(request)
        return redirect(reverse('home'))


class ProfileView(View):
    def get(self, request, username):
        profile = get_object_or_404(Profile, username=username)
        posts = profile.post_set.all()
        comments = profile.comment_set.all()
        if request.user.is_authenticated:
            following = request.user.following.all()
            following_username = [user.following.username for user in following]
        else:
            following_username = []
        if profile:
            context = {
                'profile': profile,
                'posts': posts,
                'comments': comments,
                'following_username': following_username
            }
            return render(request, 'profile.html', context)
        return redirect(reverse('home'))


class FollowToggle(LoginRequiredMixin, View):
    def post(self, request, username, *args, **kwargs):
        following_user = get_object_or_404(Profile, username=username)
        if request.user.following.filter(following=following_user).exists():
            follow_obj = Follow.objects.get(follower=request.user, following=following_user)
            follow_obj.delete()
        else:
            follow_obj = Follow(follower=request.user, following=following_user)
            follow_obj.save()

        return redirect('profile', username=following_user.username)


class SettingsView(LoginRequiredMixin, View):
    def get(self, request):
        profile = Profile.objects.get(username=request.user.username)

        profile_form = ProfileModelForm(instance=profile)
        basic_form = BasicModelForm(instance=profile.basic)
        coding_form = CodingModelForm(instance=profile.coding)
        work_form = WorkModelForm(instance=profile.work)
        context = {
            'profile': profile,
            'profile_form': profile_form,
            'basic_form': basic_form,
            'coding_form': coding_form,
            'work_form': work_form,
        }
        return render(request, "settings.html", context)

    def post(self, request):
        profile = Profile.objects.get(username=request.user.username)
        profile_form = ProfileModelForm(data=request.POST, files=request.FILES, instance=profile)
        basic_form = BasicModelForm(data=request.POST or None, instance=profile.basic)
        coding_form = CodingModelForm(data=request.POST or None, instance=profile.coding)
        work_form = WorkModelForm(data=request.POST or None, instance=profile.work)

        if profile_form.is_valid() and basic_form.is_valid() and coding_form.is_valid() and work_form.is_valid():

            for form in [profile_form, basic_form, coding_form, work_form]:
                form.save()

        return redirect('settings')

users/templates/login.html
{% extends 'free_base.html' %}

{% load static %}

{% block free %}
    <section class="bg-gray-50 dark:bg-black">
        <div class="flex flex-col items-center justify-center px-6 py-8 mx-auto md:h-screen lg:py-0">
          <a href="#" class="flex items-center mb-6 text-2xl font-semibold text-gray-900 dark:text-white">
              <img class="w-8 h-8 mr-2" src="{% static 'icon.png' %}" alt="logo">
              DevUz
          </a>
          <div class="w-full bg-white rounded-lg shadow border border-zinc-800 md:mt-0 sm:max-w-md xl:p-0 dark:bg-zinc-900 dark:border-zinc-800">
              <div class="p-6 space-y-4 md:space-y-6 sm:p-8">
                  <h1 class="text-xl font-bold leading-tight tracking-tight text-black md:text-2xl dark:text-white">
                      Login
                  </h1>
                  <form method="POST" class="space-y-4 md:space-y-6" action="{% url 'login' %}">
                      {% csrf_token %}
                      <div>
                          <label for="id_username" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">{{ form.username.label }}</label>
                          {{ form.username }}
                          {% if form.non_field_errors or form.username.errors %}
                              <ul class="max-w-md space-y-1 mt-2 list-disc list-inside">
                                  {% for error in form.non_field_errors %}
                                        <li class="text-xs text-red-500">{{ error }}</li>
                                    {% endfor %}
                              </ul>
                          {% endif %}
                          {% if form.username.errors %}
                              <ul class="max-w-md space-y-1 mt-2 list-disc list-inside">
                                  {% for error in form.username.errors %}
                                        <li class="text-xs text-red-500">{{ error }}</li>
                                    {% endfor %}
                              </ul>
                          {% endif %}
                      </div>
                      <div>
                          <label for="id_password" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Password</label>
                          {{ form.password }}
                          {% if form.password.errors %}
                              <ul class="max-w-md space-y-1 mt-2 list-disc list-inside">
                                  {% for error in form.username.errors %}
                                        <li class="text-xs text-red-500">{{ error }}</li>
                                    {% endfor %}
                              </ul>
                          {% endif %}
                      </div>
                      <hr class="h-px my-8 bg-gray-200 border-0 dark:bg-gray-700">

                      <button type="submit" class="text-purple-700 font-bold border-2 border-purple-700 hover:bg-purple-700 hover:text-white w-full rounded-lg text-sm px-5 py-2.5 mr-2 mb-2">Login</button>
                      <p class="text-sm font-light text-gray-500 dark:text-gray-400">
                          You have no account? <a href="{% url 'register' %}" class="font-medium text-primary-600 hover:text-purple-700 dark:text-primary-500">Register here</a>
                      </p>
                  </form>
              </div>
          </div>
      </div>
    </section>
{% endblock %}

users/templates/logout.html
{% extends 'base.html' %}

{% block title %}

{% endblock %}

{% block content %}
 <section class="my-auto items-center justify-center dark:bg-gray-900">
    <div class="py-8 px-4 mx-auto max-w-screen-xl lg:py-16 lg:px-6">
        <div class="mx-auto max-w-screen-sm text-center">
            <form method="post" action="{% url 'logout' %}">
                {% csrf_token %}
                <p class="mb-4 text-3xl tracking-tight font-bold text-gray-900 md:text-4xl dark:text-white">Are you sure you want to log out?</p>
                <p class="mb-4 text-lg font-light text-gray-500 dark:text-gray-400"><button type="submit" class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800">Yes, log out</button></p>
            </form>
        </div>
    </div>
</section>
{% endblock %}

users/templates/registration.html
{% extends 'free_base.html' %}

{% load static %}

{% block free %}
    <section class="bg-gray-50 dark:bg-black">
      <div class="flex flex-col items-center justify-center px-6 py-8 mx-auto md:h-screen lg:py-0">
          <a href="/" class="flex items-center mb-6 text-2xl font-bold text-black dark:text-white">
              <img class="w-8 h-8 mr-2" src="{% static 'icon.png' %}" alt="logo">
              DevUz
          </a>
          <div class="w-full bg-white rounded-lg shadow border md:mt-0 sm:max-w-md xl:p-0 dark:bg-zinc-900 dark:border-zinc-800">
              <div class="p-6 space-y-4 md:space-y-6 sm:p-8">
                  <h1 class="text-xl font-bold leading-tight tracking-tight text-gray-900 md:text-2xl dark:text-white">
                      Create an account
                  </h1>
                  <form method="POST" class="space-y-4 md:space-y-6" action="{% url 'register' %}">
                      {% csrf_token %}
                      <div>
                          <label for="id_username" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">{{ form.username.label }}</label>
                          {{ form.username }}
                          <ul class="max-w-md space-y-1 mt-2 list-disc list-inside">
                              {% for error in  form.username.errors %}
                                <li class="text-sm text-red-500">{{ error }}</li>
                              {% endfor %}
                          </ul>
                      </div>
                      <div>
                          <label for="id_email" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">{{ form.email.label }}</label>
                          {{ form.email }}
                          <ul class="max-w-md space-y-1 mt-2 list-disc list-inside">
                              {% for error in  form.email.errors %}
                                <li class="text-sm text-red-500">{{ error }}</li>
                              {% endfor %}
                          </ul>

                      </div>
                      <div>
                          <label for="id_password1" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Password</label>
                          {{ form.password1 }}
                          <ul class="max-w-md space-y-1 mt-2 list-disc list-inside">
                              {% for error in  form.password1.errors %}
                                <li class="text-sm text-red-500">{{ error }}</li>
                              {% endfor %}
                          </ul>
                      </div>
                      <div>
                          <label for="id_password2" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Confirm password</label>
                          {{ form.password2 }}

                          <ul class="max-w-md space-y-1 mt-2 list-disc list-inside">
                          {% for error in  form.password2.errors %}
                              <li class="text-sm text-red-500">{{ error }}</li>
                          {% endfor %}
                          </ul>
                      </div>
                      <hr class="h-px my-8 bg-gray-200 border-0 dark:bg-gray-700">

                      <button type="submit" class="text-purple-700 font-bold border-2 border-purple-700 hover:bg-purple-700 hover:dark:border-white hover:text-white w-full rounded-lg text-sm px-5 py-2.5 mr-2 mb-2">Save</button>
                      <p class="text-sm font-light text-gray-500 dark:text-gray-400">
                          Already have an account? <a href="#" class="font-medium text-primary-600 hover:text-purple-700">Login here</a>
                      </p>
                  </form>
              </div>
          </div>
      </div>
    </section>
{% endblock %}

users/templates/settings.html
{% extends 'base.html' %}

{% block title %}
Settings-for-{{ profile.username }}
{% endblock %}

{% block content %}
    <div class="px-4 max-w-screen-lg m-auto">
        <p class="px-4 py-6 font-extrabold text-4xl text-black dark:text-white">Settings for
            <a href="{% url 'profile' profile.username %}" class="font-extrabold text-purple-700 hover:underline">@{{ profile.username }}</a>
        </p>
        <div class="w-full grid grid-cols-1 lg:grid-cols-4 xl:grid-cols-4 2xl:grid-cols-4 gap-4">
            <div class="h-fit rounded-lg">
                <ul>
                    <li class="p-2 rounded-lg hover:bg-purple-700 hover:text-white">
                        <a class="text-gray-700 rounded-md dark:text-white" href="#">
                            <svg xmlns="http://www.w3.org/2000/svg" width="28" height="28" viewBox="0 0 24 24" role="img" class="inline">
                                <path d="M22 12c0 5.523-4.477 10-10 10S2 17.523 2 12 6.477 2 12 2s10 4.477 10 10z" fill="#FFCC4D"></path>
                                <path d="M7.842 15.123c.025.1.649 2.433 4.158 2.433 3.51 0 4.133-2.333 4.158-2.433a.277.277 0 00-.464-.265c-.011.01-1.086 1.03-3.695 1.03-2.607 0-3.683-1.02-3.692-1.03a.28.28 0 00-.452.087.278.278 0 00-.014.178zM10.056 9.5c0 1.074-.622 1.944-1.39 1.944-.767 0-1.388-.87-1.388-1.944 0-1.074.621-1.944 1.389-1.944.767 0 1.389.87 1.389 1.944zm6.666 0c0 1.074-.621 1.944-1.389 1.944-.767 0-1.389-.87-1.389-1.944 0-1.074.622-1.944 1.39-1.944.767 0 1.388.87 1.388 1.944z" fill="#664500"></path>
                            </svg>
                            <span class="mx-2 font-medium">Profile</span>
                        </a>
                    </li>
                    <li class="p-2 rounded-lg hover:bg-purple-700 hover:text-white">
                        <a class="text-gray-700 rounded-md dark:text-white" href="#">
                            <svg xmlns="http://www.w3.org/2000/svg" width="28" height="28" viewBox="0 0 24 24" role="img" class="inline">
                                <path d="M12 16.444a4.444 4.444 0 110-8.889 4.444 4.444 0 010 8.89zm8.889-6.11H19.02a7.16 7.16 0 00-.879-2.12l1.322-1.32a1.112 1.112 0 000-1.572l-.786-.786a1.11 1.11 0 00-1.571 0l-1.321 1.322a7.167 7.167 0 00-2.12-.88V3.112A1.111 1.111 0 0012.557 2h-1.112a1.11 1.11 0 00-1.11 1.111V4.98a7.167 7.167 0 00-2.12.879l-1.32-1.322a1.111 1.111 0 00-1.572 0l-.786.786a1.112 1.112 0 000 1.571l1.322 1.321a7.172 7.172 0 00-.88 2.12H3.112A1.111 1.111 0 002 11.443v1.112a1.11 1.11 0 001.111 1.11H4.98c.18.76.48 1.473.879 2.119l-1.322 1.322a1.112 1.112 0 000 1.571l.786.786a1.113 1.113 0 001.571 0l1.321-1.322c.655.405 1.37.702 2.12.88v1.867A1.111 1.111 0 0011.443 22h1.112a1.111 1.111 0 001.11-1.111V19.02c.76-.18 1.473-.48 2.119-.879l1.322 1.322a1.108 1.108 0 001.571 0l.786-.786a1.111 1.111 0 000-1.571l-1.322-1.321a7.16 7.16 0 00.88-2.12h1.867A1.111 1.111 0 0022 12.557v-1.112a1.111 1.111 0 00-1.111-1.11z" fill="#66757F"></path>
                            </svg>
                            <span class="mx-2 font-medium">Customization</span>
                        </a>
                    </li>
                </ul>
            </div>

            <div class="h-fit rounded-lg lg:col-span-3 dark:bg-black mb-10">
                   <form method="POST" enctype="multipart/form-data">
                       {% csrf_token %}
                       <div class="bg-white mb-3 py-4 rounded-lg dark:bg-zinc-900">
                          <div class="p-4 mx-auto">
                              <h2 class="mb-4 text-2xl font-bold text-black dark:text-white">User</h2>
                              <div class="grid grid-cols-2 gap-6">
                                  <div class="col-span-2">
                                      <label for="name" class="block mb-2 text-sm font-medium text-black dark:text-white">First name</label>
                                      {{ profile_form.first_name }}
                                  </div>
                                  <div class="col-span-2">
                                      <label for="name" class="block mb-2 text-sm font-medium text-black dark:text-white">Last name</label>
                                      {{ profile_form.last_name }}
                                  </div>
                                  <div class="col-span-2 ">
                                      <label for="name" class="block mb-2 text-sm font-medium text-black dark:text-white">Email</label>
                                      {{ profile_form.email }}
                                  </div>
                                  <div class="col-span-2 ">
                                      <label for="id_display_email" class="dark:hover:bg-black rounded-lg p-1 block text-sm font-medium text-black dark:text-gray-300">{{ profile_form.display_email }} <span class="ml-2">Display email on profile</span></label>
                                  </div>
                                  <div class="col-span-2">
                                      <label for="name" class="block mb-2 text-sm font-medium text-black dark:text-white">Username</label>
                                      <p id="disabled-input" class="border border-gray-300 text-black font-medium text-sm rounded-lg w-full p-2.5 focus:ring-purple-700 focus:border-purple-700 dark:bg-black dark:border-zinc-700 dark:placeholder-gray-400 dark:hover:border-zinc-600 dark:text-white cursor-not-allowed" disabled>@{{ profile.username }}</p>
                                  </div>
                                  <div class="col-span-2">
                                      <label class="block mb-2 text-sm font-medium text-black dark:text-white" for="file_input">Upload file</label>
                                          <div class="grid grid-cols-10">
                                              <img class="w-10 h-10 col-span-1 object-cover rounded-full" src="{{ profile.image.url}}" alt="Rounded avatar">
                                              {{ profile_form.image }}
                                          </div>
                                      </div>
                                  </div>
                          </div>
                       </div>

                       <div class="bg-white mb-3 py-4 rounded-lg dark:bg-zinc-900">
                          <div class="p-4 mx-auto">
                              <h2 class="mb-4 text-2xl font-bold text-black dark:text-white">Basic</h2>
                                  <div class="grid grid-cols-2 gap-6">
                                      <div class="col-span-2">
                                          <label for="name" class="block mb-2 text-sm font-medium text-black dark:text-white">Website URL</label>
                                        {{ basic_form.site }}
                                      </div>
                                      <div class="col-span-2">
                                          <label for="name" class="block mb-2 text-sm font-medium text-black dark:text-white">Location</label>
                                        {{ basic_form.location }}
                                      </div>
                                      <div class="col-span-2">
                                          <label for="name" class="block mb-2 text-sm font-medium text-black dark:text-white">Bio</label>
                                        {{ basic_form.bio }}
                                      </div>
                                  </div>
                          </div>
                        </div>

                       <div class="bg-white mb-3 py-4 rounded-lg dark:bg-zinc-900">
                          <div class="p-4 mx-auto">
                              <h2 class="mb-4 text-2xl font-bold text-black dark:text-white">Coding</h2>
                                  <div class="grid grid-cols-2 gap-6">
                                      <div class="col-span-2">
                                          <label for="name" class="block mb-2 text-sm font-medium text-black dark:text-white">Currently learning</label>
                                        {{ coding_form.current }}
                                      </div>
                                      <div class="col-span-2">
                                          <label for="name" class="block mb-2 text-sm font-medium text-black dark:text-white">Skills/Languages</label>
                                        {{ coding_form.skills }}
                                      </div>
                                  </div>
                          </div>
                        </div>

                       <div class="bg-white mb-3 py-4 rounded-lg dark:bg-zinc-900">
                          <div class="p-4 mx-auto">
                              <h2 class="mb-4 text-2xl font-bold text-black dark:text-white">Work</h2>
                                  <div class="grid grid-cols-2 gap-6">
                                      <div class="col-span-2">
                                          <label for="name" class="block mb-2 text-sm font-medium text-black dark:text-white">Work</label>
                                          {{ work_form.work }}
                                      </div>

                                      <div class="col-span-2">
                                          <label for="name" class="block mb-2 text-sm font-medium text-black dark:text-white">Education</label>
                                        {{ work_form.education }}
                                      </div>
                                  </div>
                          </div>
                        </div>

                       <div class="bg-white mb-3 p-5 rounded-lg dark:bg-zinc-900">
                            <button type="submit" class="text-white w-full bg-purple-700 hover:bg-purple-800 focus:ring-4 focus:ring-purple-900 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2">Save Profile Information</button>
                       </div>
                   </form>
            </div>
        </div>
    </div>
{% endblock %}