Dev/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('post.urls')),
    path('', include('tag.urls')),
    path('', include('users.urls')),
    path('dashboard/', include('dashboard.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/urls.py
from django.urls import path

from .views import HomeView, CreatePostView, PostView, postUpdate


urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('<str:username>/<int:pk>/', PostView.as_view(), name='post'),
    path('<str:username>/<int:pk>/updat/', postUpdate, name='post-update'),
    path('new-post', CreatePostView.as_view(), name='new-post'),
]

post/models.py
from django.contrib.auth.models import User
from django.db import models

from users.models import Profile
from tag.models import Tag


class Post(models.Model):
    class Meta:
        ordering = ['-created', 'updated']

    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="post_images", null=True, blank=True)
    title = models.CharField(max_length=150)
    tags = models.ManyToManyField(Tag, blank=True)
    content = models.TextField()
    likes = models.PositiveIntegerField(default=0)

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


class Comment(models.Model):
    class Meta:
        ordering = ['-created']

    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    body = models.TextField()

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.body


class ReadingList(models.Model):
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.profile.username}{self.post.title[:20]}'

    class Meta:
        unique_together = ('profile', 'post')

tag/models.py
from django.db import models
from django.urls import reverse_lazy

from users.models import Profile


# Create your models here.


class Tag(models.Model):
    COLORS = [
        ('DF', 'blue'),
        ('DK', 'gray'),
        ('RD', 'red'),
        ('GR', 'green'),
        ('YL', 'yellow'),
        ('ID', 'indigo'),
        ('PP', 'purple'),
        ('PK', 'pink'),
    ]
    name = models.CharField(max_length=50)
    description = models.CharField(max_length=256, null=True, blank=True)
    color = models.CharField(max_length=2, choices=COLORS, default='DF')

    def __str__(self):
        return f"# {self.name}"


class FollowingTags(models.Model):
    class Meta:
        default_related_name = 'following_tags'

    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
    tag = models.ForeignKey(Tag, on_delete=models.CASCADE)

    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.profile} follows {self.tag}'

post/forms.py
from django import forms

from post.models import Post, Tag, Comment


text_input_class = 'border border-gray-300 text-black font-semibold text-sm rounded-lg w-full p-2.5 ' \
                   'focus:ring-purple-700 focus:border-purple-700 dark:bg-black dark:border-neutral-700 ' \
                   'dark:placeholder-gray-400 dark:hover:border-neutral-600 dark:text-white'


class PostModelForm(forms.ModelForm):
    image = forms.ImageField(widget=forms.ClearableFileInput(attrs={'class': 'hidden'}))
    tags = forms.ModelMultipleChoiceField(
        queryset=Tag.objects.all(),
        widget=forms.SelectMultiple(attrs={
            'class': text_input_class,
            'required': False
        }))
    content = forms.CharField(widget=forms.Textarea(attrs={
        'class': text_input_class, 'placeholder': 'Write your post content', 'rows': 6, 'id': 'content'
    }))

    title = forms.CharField(widget=forms.TextInput(attrs={
        'class': text_input_class, 'placeholder': 'Write a title...'
    }))

    class Meta:
        model = Post
        fields = ['image', 'title', 'tags', 'content']


class CommentModelForm(forms.ModelForm):
    body = forms.CharField(required=True, label='comment', widget=forms.Textarea(attrs={
        'class': 'p-2 w-full text-sm text-gray-900 border border-neutral-700 rounded-lg dark:text-white focus:ring-1 '
                 'focus:ring-purple-700 dark:placeholder-gray-400 dark:bg-black',
        'rows': 6,
        'placeholder': 'Write a comment...'}))

    class Meta:
        model = Comment
        fields = ['body', ]

post/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.views import View

from post.forms import PostModelForm, CommentModelForm
from post.models import Post, Comment
from users.models import Profile


# Create your views here.

class HomeView(View):
    def get(self, request):
        posts = Post.objects.all()
        context = {
            'posts': posts
        }
        return render(request, 'home.html', context)


class PostView(View):
    def get(self, request, pk, username):
        post_obj = Post.objects.get(pk=pk)
        if post_obj is None:
            return redirect('/')
        comments = Comment.objects.filter(post=post_obj)
        form = CommentModelForm()
        context = {
            'post': post_obj,
            'form': form,
            'comments': comments
        }
        return render(request, 'post.html', context)

    def post(self, request, pk, username):
        if request.user.is_authenticated:
            form = CommentModelForm(data=request.POST or None)
            post_obj = Post.objects.get(pk=pk)
            profile = Profile.objects.get(username=request.user.username)

            if form.is_valid():
                new_comment = form.save(commit=False)
                new_comment.post = post_obj
                new_comment.profile = profile
                form.save()
                return redirect('post', post_obj.profile.username, post_obj.pk)
        else:
            return redirect('login')


class CreatePostView(LoginRequiredMixin, View):
    def get(self, request):
        form = PostModelForm()
        context = {
            'form': form
        }
        return render(request, 'post-create.html', context)

    def post(self, request):
        form = PostModelForm(data=request.POST or None, files=request.FILES)
        profile = Profile.objects.get(username=request.user.username)
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.profile = profile
            new_post.save()
            form.save_m2m()
            return redirect('post', new_post.profile.username, new_post.pk)


def postUpdate(request, pk, username):
    obj = Post.objects.filter(pk=pk).first()
    if not obj:
        return redirect('home')
    form = PostModelForm(data=request.POST or None, files=request.FILES, instance=obj)
    if form.is_valid():
        form.save()
        return redirect('post')

    else:
        form = PostModelForm(instance=obj)
        context = {
            'form': form
        }
        return render(request, 'post-update.html', context)

post/templates/post-create.html
{% extends 'base.html' %}


{% block title %}crate-a-post{% endblock %}

{% block content %}
    <div class="lg:w-8/12 m-auto mt-6 mb-12 mt-5">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="overflow-hidden rounded-xl space-y-6 bg-white dark:bg-zinc-900 p-6 pb-10    ">
                <div>
                    <label class="block text-sm mb-2 font-medium text-gray-900 dark:text-white" for="id_image">Post image</label>
                    <div class="flex items-center justify-center w-full">
                        <label for="id_image" class="flex flex-col items-center justify-center w-full h-40 border-2 border-zinc-800 border-dashed rounded-lg cursor-pointer bg-gray-50 dark:bg-black dark:border-zinc-700 dark:hover:border-zinc-600">
                            <div class="flex flex-col items-center justify-center pt-5 pb-6">
                                <svg aria-hidden="true" class="w-10 h-10 mb-3 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M7 16a4 4 0 01-.88-7.903A5 5 0 1115.9 6L16 6a5 5 0 011 9.9M15 13l-3-3m0 0l-3 3m3-3v12"></path></svg>
                                <p class="mb-2 text-sm text-gray-500 dark:text-gray-400"><span class="font-semibold">Click to upload</span> or drag and drop</p>
                                <p class="text-xs text-gray-500 dark:text-gray-400">SVG, PNG, JPG or GIF</p>
                            </div>
                            {{ form.image }}
                        </label>
                    </div>
                </div>
                <div class="">
                    <label for="title" class="dark:text-white mb-3 block text-sm font-medium text-gray-700">Post Title</label>
                    {{ form.title }}
                </div>
                <div>
                    <label for="tags" class="w-full dark:text-white mb-3 block text-sm font-medium text-gray-700">Post Tags
                        <a href="http://127.0.0.1:8000/admin/tag/tag/add/" class="inline text-white hover:text-purple-700 font-extrabold rounded-full text-md p-2.5 text-center mr-2">+
                        </a>
                    </label>
                    {{ form.tags }}
                    {% for foo in form.tags.option %}
                        {{ foo }}
                    {% endfor %}
                </div>
                <div class="mt-5">
                    <label for="content" class="dark:text-white mb-3 block text-sm font-medium text-gray-700">Post Content</label>
                    <div class="mt-1">
                        {{ form.content }}
                    </div>
                </div>

                <button type="submit" class="text-purple-700 font-bold border-2 border-purple-700 hover:bg-purple-700 hover:text-white w-full rounded-lg text-sm px-5 py-2.5 mr-2 mb-2">Save</button>

            </div>
        </form>
    </div>

{% endblock %}

post/templates/post-update.html
{% extends 'base.html' %}


{% block title %}Update post ({{ post.title }}){% endblock %}

{% block content %}
    <div class="lg:w-8/12 m-auto mt-6 dark:bg-gray-900">
        <div class="mt-5 md:col-span-2 dark:bg-gray-900 md:mt-0">
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="shadow sm:overflow-hidden sm:rounded-md">
                    <div class="dark:bg-gray-800 space-y-6 bg-white px-4 py-5 sm:p-6">
                        <div>
                          <label class="dark:text-white block text-sm mb-3 font-medium text-gray-700">Post Image</label>
                          <div class="mt-1 flex justify-center rounded-md border-2 border-dashed border-gray-300 px-6 pt-5 pb-6">
                            <div class="space-y-1 text-center">
                              <svg class="mx-auto h-12 w-12 text-gray-400" stroke="currentColor" fill="none" viewBox="0 0 48 48" aria-hidden="true">
                                <path d="M28 8H12a4 4 0 00-4 4v20m32-12v8m0 0v8a4 4 0 01-4 4H12a4 4 0 01-4-4v-4m32-4l-3.172-3.172a4 4 0 00-5.656 0L28 28M8 32l9.172-9.172a4 4 0 015.656 0L28 28m0 0l4 4m4-24h8m-4-4v8m-12 4h.02" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"></path>
                              </svg>
                              <div class="flex text-sm text-gray-600">
                                <label for="file-upload" class="dark:bg-gray-800 relative cursor-pointer rounded-md bg-white font-medium text-indigo-600 focus-within:outline-none focus-within:ring-2 focus-within:ring-indigo-500 focus-within:ring-offset-2 hover:text-indigo-500">
                                  <span><svg class="mx-auto h-5 w-5 text-gray-400" stroke="currentColor" fill="none" viewBox="0 0 48 48" aria-hidden="true">
                                <path d="M28 8H12a4 4 0 00-4 4v20m32-12v8m0 0v8a4 4 0 01-4 4H12a4 4 0 01-4-4v-4m32-4l-3.172-3.172a4 4 0 00-5.656 0L28 28M8 32l9.172-9.172a4 4 0 015.656 0L28 28m0 0l4 4m4-24h8m-4-4v8m-12 4h.02" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"></path>
                              </svg></span>
                                    {{ form.image }}
                                </label>
                              </div>
                                {% if not post.image %}
                                    <p class="pl-1">or drag and drop</p>
                                    <p class="text-xs text-gray-500">PNG, JPG, GIF up to 10MB</p>
                                {% endif %}
                            </div>
                          </div>
                        </div>

                        <div class="col-span-6 sm:col-span-4">
                            <label for="title" class="dark:text-white mb-3 block text-sm font-medium text-gray-700">Post Title</label>
                            {{ form.title }}
                        </div>
                        <div>
                            <label for="tags" class="w-full dark:text-white mb-3 block text-sm font-medium text-gray-700">Post Tags
                                <a href="http://localhost:8000/admin/post/tag/add/" type="button" class="inline text-white hover:text-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-full text-sm p-2.5 text-center mr-2  dark:hover:text-blue-700 dark:focus:ring-blue-800">+
                                </a>
                            </label>
                            {{ form.tags }}
                        <div class="mt-5">
                          <label for="content" class="dark:text-white mb-3 block text-sm font-medium text-gray-700">Post Content</label>
                          <div class="mt-1">
                            {{ form.content }}
                          </div>
{#                          <p class="mt-2 text-sm text-gray-500">Brief description for your profile. URLs are hyperlinked.</p>#}
                        </div>
                        </div>


                    </div>
                    <div class="dark:bg-gray-800 bg-gray-50 px-4 py-3 text-right sm:px-6">
                        <button type="submit" class="inline-flex justify-center rounded-md border border-transparent bg-indigo-600 py-2 px-4 text-sm font-medium text-white shadow-sm hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2">Save</button>
                    </div>
                </div>
            </form>
        </div>
    </div>

{% endblock %}

post/templates/post.html
{% extends 'base.html' %}
{% load static %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}
     <div class="max-w-screen-xl grid grid-cols-12 sm:grid-cols-12 md:grid-cols-12 lg:grid-cols-12 xl:grid-cols-12 gap-2 mb-10 mx-auto">
        <aside class="col-span-1">
            <div class="sticky top-12 pt-10">
                <div class="rounded-lg flex flex-col gap-8 items-center dark:format-invert">
                    <a class="flex flex-col items-center text-black font-medium rounded-lg p-1 hover:text-white hover:bg-red-700 dark:text-gray-400">
                        <span >
                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 20 19" fill="none" role="img" aria-hidden="true" class="crayons-icon">
                                <path d="M17 11v3h3v2h-3.001L17 19h-2l-.001-3H12v-2h3v-3h2Zm1.243-9.243a6 6 0 0 1 .236 8.235l-1.42-1.418C18.39 7.05 18.32 4.66 16.827 3.17a4.001 4.001 0 0 0-5.49-.153l-1.335 1.198-1.336-1.197a3.999 3.999 0 0 0-5.494.154 4 4 0 0 0-.192 5.451l8.432 8.446L10 18.485 1.52 9.993A6 6 0 0 1 10 1.529a5.998 5.998 0 0 1 8.242.228h.001Z" fill="white"></path>
                            </svg>
                        </span>
                        <span>9</span>
                    </a>
                    <a class="flex flex-col items-center text-black font-medium rounded-lg p-1 hover:text-white hover:bg-yellow-700 dark:text-gray-400">
                        <span class="">
                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" role="img" aria-hidden="true" class="crayons-icon">
                                <path d="M10 3h4a8 8 0 010 16v3.5c-5-2-12-5-12-11.5a8 8 0 018-8zm2 14h2a6 6 0 000-12h-4a6 6 0 00-6 6c0 3.61 2.462 5.966 8 8.48V17z" fill="white"></path>
                            </svg>
                        </span>
                        <span>2</span>
                    </a>
                    <a class="flex flex-col items-center text-black font-medium rounded-lg p-1 hover:text-white hover:bg-purple-700 dark:text-gray-400">
                        <span class="">
                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" role="img" aria-hidden="true" class="crayons-icon">
                                <path d="M5 2h14a1 1 0 011 1v19.143a.5.5 0 01-.766.424L12 18.03l-7.234 4.536A.5.5 0 014 22.143V3a1 1 0 011-1zm13 2H6v15.432l6-3.761 6 3.761V4z" fill="white"></path>
                            </svg>
                        </span>
                        <span>4</span>
                    </a>
              </div>
            </div>
        </aside>
        <main class="col-span-11 rounded-lg border border-neutral-800 lg:col-span-8 dark:bg-neutral-900">
            <div class="bg-white dark:bg-neutral-900 rounded-lg">
                {% if post.image %}
                    <img class="h-80 object-cover w-full rounded-t-lg" src="{{ post.image.url }}" alt="image description">
                {% endif %}
                <div class="px-10 pb-10">
                    <div class="flex items-center space-x-4 my-4">
                        <div class="flex-shrink-0">
                            <img class="w-8 h-8 rounded-full" src="{{ post.profile.image.url }}" alt="Post image">
                        </div>
                        <div>
                            <a href="{% url 'profile' post.profile.username %}" class="text-sm font-medium text-gray-900 truncate dark:text-white">
                                {{ post.profile.username }}
                            </a>
                            <p class="text-sm text-gray-500 truncate dark:text-gray-400">
                                {{ post.created|timesince }} ago
                            </p>
                        </div>
                    </div>
                    <h1 class="mb-4 text-3xl font-extrabold text-black lg:mb-6 lg:text-5xl dark:text-white">
                        {{ post.title }}
                    </h1>
                    <div class="my-3">
                        {% for tag in post.tags.all %}
                            <a href="#" class="font-medium p-1 rounded text-{{ tag.get_color_display }}-500 hover:bg-{{ tag.get_color_display }}-500 hover:text-white transition-colors duration-300 transform">{{ tag }}</a>
                        {% endfor %}
                    </div>
                    <div class="dark:text-white mt-10 font-mono text-xl">
                        {{ post.content }}
                        {% lorem 5 %}
                    </div>
                    <div class="dark:text-white p-2 border-t-2 border-neutral-800 mt-10 font-mono text-xl">
                        <form method="post">
                            {% csrf_token %}
                                {{ form }}
                            <button type="submit" class="text-purple-700 border border-purple-700 hover:bg-purple-700 hover:text-white font-medium rounded-lg text-sm px-4 py-2 text-center mr-2">Submit</button>
                        </form>
                    </div>
                    <div class="dark:text-white p-2 mt-5">
                        {% for comment in comments %}
                            <article class="p-4  mb-6 text-base bg-white rounded-lg border dark:border-neutral-700 dark:bg-neutral-900">
                                <footer class="flex justify-between items-center mb-2">
                                    <div class="flex items-center">
                                        <p class="inline-flex items-center mr-3 text-sm text-gray-900 dark:text-white">
                                            <img class="mr-2 w-6 rounded-full dark:bg-white" src="{{ comment.profile.image.url }}" alt="{{ comment.profile.username }}">
                                            {{ comment.profile.username }}
                                        </p>
                                        <p class="text-sm text-gray-600 dark:text-gray-400">
                                            <time>{{ comment.created|timesince }} ago.</time>
                                        </p>
                                    </div>
                                    <button id="dropdownComment{{ comment.id }}Button" data-dropdown-toggle="dropdownComment{{ comment.id }}"
                                        class="inline-flex items-center p-1 font-medium text-center text-gray-400 rounded-lg hover:bg-gray-100 dark:hover:bg-neutral-800"
                                        type="button">
                                        <svg class="w-5 h-5" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20"
                                            xmlns="http://www.w3.org/2000/svg">
                                            <path
                                                d="M6 10a2 2 0 11-4 0 2 2 0 014 0zM12 10a2 2 0 11-4 0 2 2 0 014 0zM16 12a2 2 0 100-4 2 2 0 000 4z">
                                            </path>
                                        </svg>
                                    </button>
                                    <!-- Dropdown menu -->
                                    <div id="dropdownComment{{ comment.id }}"
                                        class="hidden z-10 w-36 bg-white rounded border divide-y divide-gray-100 shadow dark:border-neutral-800 dark:bg-neutral-900">
                                        <ul class="p-1 text-sm text-gray-700 dark:text-gray-200"
                                            aria-labelledby="dropdownMenuIconHorizontalButton">
                                            <li>
                                                <a href="#" class="block py-2 px-4 hover:bg-gray-100 rounded dark:hover:bg-purple-700 dark:hover:text-white">Edit</a>
                                            </li>
                                            <li>
                                                <a href="#" class="block py-2 px-4 hover:bg-gray-100 rounded dark:hover:bg-purple-700 dark:hover:text-white">Remove</a>
                                            </li>
                                            <li>
                                                <a href="#" class="block py-2 px-4 hover:bg-gray-100 rounded dark:hover:bg-purple-700 dark:hover:text-white">Report</a>
                                            </li>
                                        </ul>
                                    </div>
                                </footer>
                                <p class="text-gray-500 dark:text-gray-400">
                                    {{ comment.body }}
                                </p>

                            </article>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </main>
        <aside class="col-span-3 hidden lg:block lg:col-span-3  h-fit rounded-lg dark:bg-neutral-900">
            <div class="w-full bg-white border border-neutral-500 rounded-lg shadow dark:bg-neutral-900 dark:border-neutral-700">
                <div class="rounded-t-lg bg-black h-6 mb-2">
                </div>
                <div class="flex flex-col items-center pb-6">
                    <img class="w-20 h-20 mb-2 rounded-full dark:bg-white" src="{{ post.profile.image.url }}" alt="Bonnie image"/>
                    <a href="{% url 'profile' post.profile.username %}" class="mb-1 text-xl font-medium text-gray-900 dark:text-white">@{{ post.profile.username }}</a>
                    {% if post.profile == request.user %}
                        <div class="mt-4 w-full px-12 flex justify-center">
                            <a href="{% url 'settings' %}" class="w-full text-center text-white bg-purple-700 hover:bg-purple-800 font-medium rounded-lg text-sm px-5 py-2">Settings</a>
                        </div>
                    {% else %}
                        <p class="text-md text-gray-900 dark:text-white">{{ post.profile.basic.bio }}</p>
                        <div class="mt-4">
                            <form action="{% url 'follow_toggle' post.profile.username %}"  method="POST">
                                {% csrf_token %}
                                <button type="submit" class="text-center text-white bg-purple-700 hover:bg-purple-800 font-medium rounded-lg text-sm px-5 py-2">{% if post.profile.username in following_username %}Unfollow{% else %}Follow{% endif %}</button>
                            </form>
                        </div>
                    {% endif %}
                </div>
            </div>
        </aside>
     </div>
{% endblock %}