Dev/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('post.urls')),
    path('', include('tag.urls')),
    path('', include('users.urls')),
    path('dashboard/', include('dashboard.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/urls.py
from django.urls import path

from .views import (
    DashboardPostsView, DashboardFollowingTagsView,
    DashboardFollowingUsersView, DashboardFollowersView,
    DashboardReadingListView
)

app_name = "dashboard"

urlpatterns = [
    path('post/', DashboardPostsView.as_view(), name='posts'),
    path('folllowing-tags/', DashboardFollowingTagsView.as_view(), name='following-tags'),
    path('followers/', DashboardFollowersView.as_view(), name='followers'),
    path('following-users/', DashboardFollowingUsersView.as_view(), name='following-users'),
    path('reading-list/', DashboardReadingListView.as_view(), name='reading-list'),
]

post/urls.py
from django.urls import path

from .views import HomeView, CreatePostView, PostView, postUpdate


urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('<str:username>/<int:pk>/', PostView.as_view(), name='post'),
    path('<str:username>/<int:pk>/updat/', postUpdate, name='post-update'),
    path('new-post', CreatePostView.as_view(), name='new-post'),
]

post/models.py
from django.contrib.auth.models import User
from django.db import models

from users.models import Profile
from tag.models import Tag


class Post(models.Model):
    class Meta:
        ordering = ['-created', 'updated']

    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="post_images", null=True, blank=True)
    title = models.CharField(max_length=150)
    tags = models.ManyToManyField(Tag, blank=True)
    content = models.TextField()
    likes = models.PositiveIntegerField(default=0)

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


class Comment(models.Model):
    class Meta:
        ordering = ['-created']

    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    body = models.TextField()

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.body


class ReadingList(models.Model):
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.profile.username}{self.post.title[:20]}'

    class Meta:
        unique_together = ('profile', 'post')

tag/models.py
from django.db import models
from django.urls import reverse_lazy

from users.models import Profile


# Create your models here.


class Tag(models.Model):
    COLORS = [
        ('DF', 'blue'),
        ('DK', 'gray'),
        ('RD', 'red'),
        ('GR', 'green'),
        ('YL', 'yellow'),
        ('ID', 'indigo'),
        ('PP', 'purple'),
        ('PK', 'pink'),
    ]
    name = models.CharField(max_length=50)
    description = models.CharField(max_length=256, null=True, blank=True)
    color = models.CharField(max_length=2, choices=COLORS, default='DF')

    def __str__(self):
        return f"# {self.name}"


class FollowingTags(models.Model):
    class Meta:
        default_related_name = 'following_tags'

    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
    tag = models.ForeignKey(Tag, on_delete=models.CASCADE)

    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.profile} follows {self.tag}'

post/forms.py
from django import forms

from post.models import Post, Tag, Comment


text_input_class = 'border border-gray-300 text-black font-semibold text-sm rounded-lg w-full p-2.5 ' \
                   'focus:ring-purple-700 focus:border-purple-700 dark:bg-black dark:border-neutral-700 ' \
                   'dark:placeholder-gray-400 dark:hover:border-neutral-600 dark:text-white'


class PostModelForm(forms.ModelForm):
    image = forms.ImageField(widget=forms.ClearableFileInput(attrs={'class': 'hidden'}))
    tags = forms.ModelMultipleChoiceField(
        queryset=Tag.objects.all(),
        widget=forms.SelectMultiple(attrs={
            'class': text_input_class,
            'required': False
        }))
    content = forms.CharField(widget=forms.Textarea(attrs={
        'class': text_input_class, 'placeholder': 'Write your post content', 'rows': 6, 'id': 'content'
    }))

    title = forms.CharField(widget=forms.TextInput(attrs={
        'class': text_input_class, 'placeholder': 'Write a title...'
    }))

    class Meta:
        model = Post
        fields = ['image', 'title', 'tags', 'content']


class CommentModelForm(forms.ModelForm):
    body = forms.CharField(required=True, label='comment', widget=forms.Textarea(attrs={
        'class': 'p-2 w-full text-sm text-gray-900 border border-neutral-700 rounded-lg dark:text-white focus:ring-1 '
                 'focus:ring-purple-700 dark:placeholder-gray-400 dark:bg-black',
        'rows': 6,
        'placeholder': 'Write a comment...'}))

    class Meta:
        model = Comment
        fields = ['body', ]

dashboard/views.py
from django.shortcuts import render
from django.views import View

from post.models import Post
from tag.models import FollowingTags


# Create your views here.


class DashboardPostsView(View):
    def get(self, request):
        posts = Post.objects.filter(profile=request.user)
        context = {
            'posts': posts
        }
        return render(request, 'dashboard/posts.html', context)


class DashboardFollowingTagsView(View):
    def get(self, request):
        following_tags = request.user.following_tags.all()
        context = {
            'following_tags': following_tags
        }
        return render(request, 'dashboard/following-tags.html', context)


class DashboardFollowersView(View):
    def get(self, request):
        followers = request.user.followers.all()
        context = {
            'followers': followers
        }
        return render(request, 'dashboard/followers.html', context)


class DashboardFollowingUsersView(View):
    def get(self, request):
        following = request.user.following.all()
        context = {
           'following': following
        }
        return render(request, 'dashboard/following-users.html', context)


class DashboardReadingListView(View):
    def get(self, request):
        reading_list = request.user.readinglist_set.all()
        context = {
            'reading_list': reading_list
        }
        return render(request, 'dashboard/reading-list.html', context)

post/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.views import View

from post.forms import PostModelForm, CommentModelForm
from post.models import Post, Comment
from users.models import Profile


# Create your views here.

class HomeView(View):
    def get(self, request):
        posts = Post.objects.all()
        context = {
            'posts': posts
        }
        return render(request, 'home.html', context)


class PostView(View):
    def get(self, request, pk, username):
        post_obj = Post.objects.get(pk=pk)
        if post_obj is None:
            return redirect('/')
        comments = Comment.objects.filter(post=post_obj)
        form = CommentModelForm()
        context = {
            'post': post_obj,
            'form': form,
            'comments': comments
        }
        return render(request, 'post.html', context)

    def post(self, request, pk, username):
        if request.user.is_authenticated:
            form = CommentModelForm(data=request.POST or None)
            post_obj = Post.objects.get(pk=pk)
            profile = Profile.objects.get(username=request.user.username)

            if form.is_valid():
                new_comment = form.save(commit=False)
                new_comment.post = post_obj
                new_comment.profile = profile
                form.save()
                return redirect('post', post_obj.profile.username, post_obj.pk)
        else:
            return redirect('login')


class CreatePostView(LoginRequiredMixin, View):
    def get(self, request):
        form = PostModelForm()
        context = {
            'form': form
        }
        return render(request, 'post-create.html', context)

    def post(self, request):
        form = PostModelForm(data=request.POST or None, files=request.FILES)
        profile = Profile.objects.get(username=request.user.username)
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.profile = profile
            new_post.save()
            form.save_m2m()
            return redirect('post', new_post.profile.username, new_post.pk)


def postUpdate(request, pk, username):
    obj = Post.objects.filter(pk=pk).first()
    if not obj:
        return redirect('home')
    form = PostModelForm(data=request.POST or None, files=request.FILES, instance=obj)
    if form.is_valid():
        form.save()
        return redirect('post')

    else:
        form = PostModelForm(instance=obj)
        context = {
            'form': form
        }
        return render(request, 'post-update.html', context)

dashboard/templates/dashboard/dashboard-sidebar.html
<div class="h-fit sm:col-span-3 md:col-span-2">
    <ul class="space-y-2 text-sm font-medium text-gray-900 dark:text-white">
        <li>
            <a href="{% url 'dashboard:posts' %}" class="flex items-center p-2 text-base font-bold text-gray-900 rounded-lg dark:text-white hover:bg-purple-700">
               <span class="flex-1 ml-3 whitespace-nowrap">Posts</span>
               <span class="inline-flex items-center justify-center w-3 h-3 p-3 ml-3 text-sm font-bold text-neutral-300 bg-neutral-700 rounded-full">{{ post_count }}</span>
            </a>
        </li>
        <li>
            <a href="{% url 'dashboard:following-tags' %}" class="flex items-center p-2 text-base font-bold text-gray-900 rounded-lg dark:text-white hover:bg-purple-700">
               <span class="flex-1 ml-3 whitespace-nowrap">Following Tag</span>
               <span class="inline-flex items-center justify-center w-3 h-3 p-3 ml-3 text-sm font-bold text-neutral-300 bg-neutral-700 rounded-full">{{ following_tag_count }}</span>
            </a>
        </li>
        <li>
            <a href="{% url 'dashboard:followers' %}" class="flex items-center p-2 text-base font-bold text-gray-900 rounded-lg dark:text-white hover:bg-purple-700">
               <span class="flex-1 ml-3 whitespace-nowrap">Followers</span>
               <span class="inline-flex items-center justify-center w-3 h-3 p-3 ml-3 text-sm font-bold text-neutral-300 bg-neutral-700 rounded-full">{{ follower_count }}</span>
            </a>
        </li>
        <li>
            <a href="{% url 'dashboard:following-users' %}" class="flex items-center p-2 text-base font-bold text-gray-900 rounded-lg dark:text-white hover:bg-purple-700">
               <span class="flex-1 ml-3 whitespace-nowrap">Following Users</span>
               <span class="inline-flex items-center justify-center w-3 h-3 p-3 ml-3 text-sm font-bold text-neutral-300 bg-neutral-700 rounded-full">{{ following_count }}</span>
            </a>
        </li>
        <li>
            <a href="{% url 'dashboard:reading-list' %}" class="flex items-center p-2 text-base font-bold text-gray-900 rounded-lg dark:text-white hover:bg-purple-700">
               <span class="flex-1 ml-3 whitespace-nowrap">Reading List</span>
               <span class="inline-flex items-center justify-center w-3 h-3 p-3 ml-3 text-sm font-bold text-neutral-300 bg-neutral-700 rounded-full">{{ reading_list_count }}</span>
            </a>
         </li>
    </ul>
</div>

dashboard/templates/dashboard/dashboard_base.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Dashboard - Dev{% endblock %}

{% block content %}
    <div class="max-w-screen-xl mx-auto pb-1 mb-4 rounded-xl">
        <div class="my-2">
            <div class=" flex flex-wrap justify-start">
                <p class="text-3xl font-bold dark:text-white">Dashboard » {% block dashboard-titl %}{% endblock %}</p>
            </div>
            {% block post-card %}

            {% endblock %}
        </div>
    </div>
    <div class="grid max-w-screen-xl mx-auto sm:grid-cols-9 gap-4">
        {% include 'dashboard/dashboard-sidebar.html' %}
        {% block dashboard %}
        
        {% endblock %}
    </div>
{% endblock %}

dashboard/templates/dashboard/followers.html
{% extends 'dashboard/dashboard_base.html' %}
{% load static %}

{% block dashboard-titl %}
    Followers
{% endblock %}

{% block dashboard %}
    <div class="rounded-lg sm:col-span-6 md:col-span-7">
        <div class="">
            {% if followers %}
                <div class="space-y-8 md:grid md:grid-cols-2 lg:grid-cols-3 md:gap-4 md:space-y-0">
                    {% for user in followers %}
                        <div class="flex flex-col bg-white border rounded-lg items-center py-8 dark:bg-neutral-900 dark:border-neutral-700">
                            <img class="w-24 h-24 mb-3 rounded-full shadow-lg dark:bg-white" src="{{ user.follower.image.url }}" alt="Bonnie image"/>
                            {% if user.follower.first_name or user.follower.last_name %}
                                <h5 class="mb-1 text-xl font-medium text-gray-900 dark:text-white">{{ user.follower.firs_name }} {{ user.follower.last_name }}</h5>
                            {% endif %}
                            <a href="{% url 'profile' user.follower.username %}" class="text-sm text-gray-500 dark:text-gray-400">@{{ user.follower.username }}</a>
                        </div>
                    {% endfor %}
                </div>
            {% else %}
                <div class="flex flex-col items-center h-100">
                    <img src="https://res.cloudinary.com/practicaldev/image/fetch/s--XHE_XeFn--/c_imagga_scale,f_auto,fl_progressive,q_auto,w_300/https://dev-to-uploads.s3.amazonaws.com/i/y5767q6brm62skiyywvc.png" alt="no-post">
                    <p class="mb-6 dark:text-neutral-500">This is where you can manage your posts, but you haven't written anything yet.</p>
                </div>
            {% endif %}
        </div>
    </div>
{% endblock %}

dashboard/templates/dashboard/following-tags.html
{% extends 'dashboard/dashboard_base.html' %}
{% load static %}


{% block dashboard-titl %}
Following Tags
{% endblock %}

{% block dashboard %}
    <div class="rounded-lg sm:col-span-6 md:col-span-7">
        <div class="pb-6 rounded-lg">
            {% if following_tags %}
                <div class="space-y-8 md:grid md:grid-cols-2 lg:grid-cols-3 md:gap-8 md:space-y-0">
                    {% for tag in following_tags %}
                        <div class="rounded-lg min-h-fit dark:bg-neutral-900">
                            <div class="h-4 bg-{{ tag.tag.get_color_display }}-500 rounded-t-lg w-full">
                            </div>
                            <div class="p-3">
                                <a href="{% url 'tag' tag.tag.pk %}" class="text-xl p-2 my-2 font-bold dark:text-white hover:text-{{ tag.tag.get_color_display }}-500">#{{ tag.tag.name }}</a>
                                {% if tag.tag.description %}
                                    <p class="my-2 m text-gray-500 dark:text-gray-400">{{ tag.tag.description }}</p>
                                {% endif %}
                            </div>
                        </div>
                    {% endfor %}
                </div>
            {% else %}
                <div class="flex flex-col items-center h-100">
                    <img src="https://res.cloudinary.com/practicaldev/image/fetch/s--XHE_XeFn--/c_imagga_scale,f_auto,fl_progressive,q_auto,w_300/https://dev-to-uploads.s3.amazonaws.com/i/y5767q6brm62skiyywvc.png" alt="no-tag">
                    <p class="mb-6 dark:text-neutral-500">Follow tags to personalize your feed. You can explore popular tags here.</p>
                </div>
            {% endif %}
        </div>
    </div>
{% endblock %}

dashboard/templates/dashboard/following-users.html
{% extends 'dashboard/dashboard_base.html' %}
{% load static %}


{% block dashboard-titl %}
Following Users
{% endblock %}

{% block dashboard %}
    <div class="rounded-lg sm:col-span-6 md:col-span-7">
        <div class="pb-6">
             {% if following %}
                <div class="space-y-8 md:grid md:grid-cols-2 lg:grid-cols-3 md:gap-4 md:space-y-0">
                    {% for user in following %}
                        <div class="flex flex-col bg-white border rounded-lg items-center py-8 dark:border-neutral-700 dark:bg-neutral-900">
                            <img class="w-24 h-24 mb-3 rounded-full shadow-lg dark:bg-white" src="{{ user.following.image.url }}" alt="Bonnie image"/>
                            {% if user.following.first_name or user.following.last_name %}
                                <h5 class="mb-1 text-xl font-medium text-gray-900 dark:text-white">{{ user.following.firs_name }} {{ user.following.last_name }}</h5>
                            {% endif %}
                            <a href="{% url 'profile' user.follower.username %}" class="text-sm font-medium text-gray-500 dark:text-gray-400">@{{ user.following.username }}</a>
                        </div>
                    {% endfor %}
                </div>
             {% else %}
                <div class="flex flex-col items-center h-100">
                    <img src="https://res.cloudinary.com/practicaldev/image/fetch/s--XHE_XeFn--/c_imagga_scale,f_auto,fl_progressive,q_auto,w_300/https://dev-to-uploads.s3.amazonaws.com/i/y5767q6brm62skiyywvc.png" alt="no-post">
                    <p class="mb-6 dark:text-neutral-600">You don't follow any users...</p>
                </div>
            {% endif %}
        </div>
    </div>
{% endblock %}

dashboard/templates/dashboard/post-cards.html
<div class="space-y-2 my-3 grid grid-cols-2 gap-2 sm:grid sm:grid-cols-4 sm:gap-2 md:space-y-0">
    <div class="rounded-lg bg-neutral-900 flex flex-wrap justify-start content-center px-6 h-28">
        <div>
            <p class="text-3xl font-bold dark:text-white">0</p>
            <p class="text-md text-gray-700 dark:text-neutral-400">Total post reactions</p>
        </div>
    </div>
    <div class="rounded-lg bg-neutral-900 flex flex-wrap justify-start content-center px-6 h-28">
        <div>
            <p class="text-3xl font-bold dark:text-white">0</p>
            <p class="text-md text-gray-700 dark:text-neutral-400">Total post views</p>
        </div>
    </div>
    <div class="rounded-lg bg-neutral-900 flex flex-wrap justify-start content-center px-6 h-28">
        <div>
            <p class="text-3xl font-bold dark:text-white">0</p>
            <p class="text-md text-gray-700 dark:text-neutral-400">#</p>
        </div>
    </div>
    <div class="rounded-lg bg-neutral-900 flex flex-wrap justify-start content-center px-6 h-28">
        <div>
            <p class="text-3xl font-bold dark:text-white">0</p>
            <p class="text-md text-gray-700 dark:text-neutral-400">#</p>
        </div>
    </div>
</div>

dashboard/templates/dashboard/posts.html
{% extends 'dashboard/dashboard_base.html' %}
{% load static %}

{% block post-card %}
    {% include 'dashboard/post-cards.html' %}
{% endblock %}

{% block dashboard-titl %}
    Post
{% endblock %}

{% block dashboard %}
    <div class="rounded-lg sm:col-span-6 md:col-span-7">
        <p class="text-xl font-bold mb-4 dark:text-white">Post</p>
        <div class="pb-6 rounded-lg">
            {% if posts %}
                {% for post in posts %}
                    <div class="border border-neutral-800 overflow-hidden mb-3 rounded-lg dark:bg-neutral-900 dark:hover:bg-black">
                      <nav class="flex flex-col items-start justify-between p-4 space-y-3 md:flex-row md:items-center md:space-y-0" aria-label="Table navigation">
                          <div class="flex flex-col items-start">
                            <a href="{% url 'post' post.profile.username post.id %}" class="text-md font-bold text-blue-700 dark:text-gray-400">{{ post.title }}</a>
                            <span class="text-sm font-normal text-gray-500 dark:text-gray-400">Published: {{ post.created|timesince }} ago</span>
                          </div>
                          <div class="flex flex-col gap-2">
                            <a href="" class="text-ms font-normal hover:text-blue-700 text-gray-500 dark:text-gray-400">Edite</a>
                            <a href="" class="text-sm font-normal hover:text-blue-700 text-gray-500 dark:text-gray-400">Delete</a>
                          </div>
                      </nav>
                    </div>
                {% endfor %}
            {% else %}
                <div class="flex flex-col items-center h-100">
                    <img src="https://res.cloudinary.com/practicaldev/image/fetch/s--XHE_XeFn--/c_imagga_scale,f_auto,fl_progressive,q_auto,w_300/https://dev-to-uploads.s3.amazonaws.com/i/y5767q6brm62skiyywvc.png" alt="no-post">
                    <p class="mb-6">This is where you can manage your posts, but you haven't written anything yet.</p>
                    <p><a href="{% url 'new-post' %}" class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800">Write your first post now</a></p>
                </div>
            {% endif %}
        </div>
    </div>
{% endblock %}

dashboard/templates/dashboard/reading-list.html
{% extends 'dashboard/dashboard_base.html' %}
{% load static %}

{% block dashboard-titl %}
Reading List
{% endblock %}

{% block dashboard %}
    <div class="rounded-lg xl:col-span-7 2xl:col-span-7 dark:bg-gray-900">
        <div class="pb-6">
            {% if reading_list %}
                {% for post in reading_list %}
                    <div class="relative ring-gray-300 ring-1 overflow-hidden mb-3 bg-white rounded-lg dark:bg-gray-800">
                      <nav class="p-4" aria-label="Table navigation">
                          <div class="flex flex-row gap1">
                              <img class="w-10 h-10 rounded-full mr-2" src="{{ post.post.profile.image.url }}" alt="Post user image">
                              <div class="flex flex-col items-start">
                                <a href="{% url 'post' post.post.profile.username post.id %}" class="text-md font-bold text-blue-700 dark:text-gray-400">{{ post.post.title }}</a>
                                <div>
                                    <a href="{% url 'profile' post.post.profile.username %}" class="text-sm text-gray-600 dark:text-gray-500 font-semibold text-gray-800 transition-colors duration-300 transform dark:text-white hover:text-gray-600 hover:underline">@{{ post.post.profile.username }}
                                    </a>
                                    <span class="text-xs font-normal text-gray-500 dark:text-gray-400">
                                        created at {{ post.post.created|timesince }}
                                    </span>
                                    {% for tag in post.post.tags.all %}
                                        <a href="" class="text-xs ml-3 text-{{ tag.get_color_display }}-600 dark:text-{{ tag.get_color_display }}-500 font-semibold text-gray-800 transition-colors duration-300 transform dark:text-white hover:text-gray-600 hover:underline"># {{ tag.name }}</a>
                                    {% endfor %}
                                </div>
                              </div>
                          </div>
                      </nav>
                    </div>
                {% endfor %}
            {% else %}
                <div class="flex flex-col mb-6 items-center h-100">
                    <img src="https://res.cloudinary.com/practicaldev/image/fetch/s--XHE_XeFn--/c_imagga_scale,f_auto,fl_progressive,q_auto,w_300/https://dev-to-uploads.s3.amazonaws.com/i/y5767q6brm62skiyywvc.png" alt="no-post">
                    <h2 class="mb-6 fw-bold fs-l">Your reading list is empty</h2>
                </div>
            {% endif %}
        </div>
    </div>
{% endblock %}